services:
  zibian-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/sync_dockerhub/zibian-frontend:v1.0.0
    container_name: zibian-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
